---
- hosts: agent
  connection: ssh
  become: yes
  become_method: sudo
  tasks: 
    - name: Install apache server 
      yum:
        name=httpd
        state=present
    
    - name: start httpd service 
      service: 
        name=httpd  
        state=started 
        enabled=yes
   
    - name: copy the index.html file
      copy: 
        src=/tmp/index.html 
        dest=/var/www/html/index.html 
        mode=0644
 
    - name: stop iptables
      command: systemctl stop firewalld 
  
#    - name: save iptables 
#     command: systemctl save firewalld
